### ISSUE TITLE
Sort out how build project 

### ISSUE THREAD

**Issue by andriivoronkin** [dictor93/girland#10]
I have built an example, but cannot build this project

**Comment by dictor93** [comment]
@andriivoronkin . What kind of problems?
Make sure that you using a relative path to the `common.mk` file, that located in your `idf` instance folder: https://github.com/dictor93/girland/blob/master/Makefile#L12

Also, probably, you have no src folder in the project folder. As it was empty before i added branch related to the wifi, so, according to this case git had no indexed this folder, but makefile has a link to this folder.
https://github.com/dictor93/girland/blob/master/Makefile#L5
To solve this part of this issue i imagine two different ways:
1. Remove link to the /src folder from your local makefile, but it can make some difficulties with git in the future.
2. The other way allows to avoid git issues - just create ./src folder in the root of your instance of the project. As it is empty - it'll be invisible for git, until wifi branch will be merged.
